version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: alurafood-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: alurafood-pedidos
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: some-rabbit
    hostname: my-rabbit
    ports:
      - "15672:15672" # Porta para o RabbitMQ Management Plugin (interface web)
      - "5672:5672"   # Porta para o protocolo AMQP

volumes:
  mysql-data:
